# Generated by Django 5.2.17 on 2026-09-14 04:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('event_management', 'Event Management'), ('writing', 'Writing'), ('business_case', 'Business Case'), ('product_management', 'Product Management')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('photo_bw', models.URLField()),
                ('photo_color', models.URLField()),
            ],
        ),
    ]
