# Generated by Django 5.2.17 on 2026-09-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='organization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='experience',
            name='period',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
